# Generated by Django 4.0.5 on 2022-06-14 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futbolec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='equipos',
            field=models.ManyToManyField(through='futbolec.Campeonato_equipo', to='futbolec.equipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='campeonatos',
            field=models.ManyToManyField(through='futbolec.Campeonato_equipo', to='futbolec.campeonato'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='futbolec.equipo'),
        ),
    ]
