# Generated by Django 4.0.5 on 2022-06-14 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futbolec', '0003_alter_campeonato_equipo_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato_equipo',
            name='campeonato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campeonatos_eq', to='futbolec.campeonato'),
        ),
        migrations.AlterField(
            model_name='campeonato_equipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campeonatos_eq', to='futbolec.equipo'),
        ),
    ]
